apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
#  type: LoadBalancer
  type: NodePort
  ports:
    - port: 8001
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress

