kind: PersistentVolume
apiVersion: v1
metadata:
  name: wordpress-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: wordpress-volumeclaim
  hostPath:
    path: "/root/my_test_vol_wp"

