
apiVersion: v1
kind: Pod
metadata:
  name: cm-env-var
spec:
  volumes:
    - name: cm-vol
      secret:
        secretName: osconf
  containers:
    - name: n1
      image: ubuntu:trusty
      command:
        - "bin/bash"
        - "-c"
        - "sleep 2000000"
      envFrom:
        - configMapRef:
            name: example-cm
      volumeMounts:
        - name: cm-vol          
          mountPath: "/tmp/apikey"
          readOnly: true
