apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: mypod
      labels:
        app: alone
    spec:
      containers:
        - name: n1
          image: tomcat
          ports:
           - containerPort: 80

