apiVersion: v1
kind: Pod
metadata:
  name: pv-pod1
  labels:
    app: pv-pod1
spec:
  volumes:
    - name: pv-storage1
      persistentVolumeClaim:
        claimName: pv-vol-claim
  containers:
    - name: cont1
      image: nginx
      volumeMounts:
        - name: pv-storage1
          mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-pod2
  labels:
    app: pv-pod2
spec:
  volumes:
    - name: pv-storage1
      persistentVolumeClaim:
        claimName: pv-vol-claim
  containers:
    - name: cont1
      image: nginx
      volumeMounts:
        - name: pv-storage1
          mountPath: /usr/share/nginx/html
